//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univ_WebSite_Api_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int ClassID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Capacity { get; set; }
        public Nullable<bool> IsFull { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> LessonID { get; set; }
        public Nullable<int> GradeID { get; set; }
    }
}
