//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univ_WebSite_Api_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int TeacherID { get; set; }
        public Nullable<int> PersonID { get; set; }
    }
}
